35 récupérer tous les trajets à venir dun utilisateur
alcatel-taxi-brousse/backend pull request #36
Opened 2024-12-12 12:04 UTC by Foubel

2024-12-12 15:56 UTC, SEBPICH approved these changes

2025-01-17 13:59 UTC, maelehrhard commented on src/community/controllers/trip.controller.ts
> +@Controller()
Can you please keep the prefix ?

2025-01-17 14:00 UTC, maelehrhard requested changes

2025-01-17 14:00 UTC, maelehrhard commented on src/community/controllers/trip.controller.ts
> +@Controller()
Can you please keep the prefix ?

2025-01-17 14:22 UTC, maelehrhard approved these changes

2025-01-17 14:57 UTC, merged