Added route to search communities
alcatel-taxi-brousse/backend pull request #38
Opened 2024-12-13 22:43 UTC by axelmunch

2024-12-14 13:58 UTC, maelehrhard requested changes

2024-12-14 13:58 UTC, maelehrhard commented on src/community/services/community.service.ts
> +  async searchCommunities(search: string): Promise<Community[]> {
Pour le bien des performances, il vaudrait mieux effectuer la requête en SQL plutôt que charger toutes les données dans l'API (en mémoire) et y chercher la communauté. Tu peux utiliser les RawQueries.
Conseil: fais d'abord la requête en SQL, vérifie qu'elle marche puis adapte la à la syntaxe RawQueries.

2024-12-14 13:58 UTC, maelehrhard commented on src/community/services/community.service.ts
> +      //   const bubble = this.rainbow.bubbles.getBubbleById(community.community_id);
Peux-tu enlever le code commenté ?

2024-12-14 14:59 UTC, axelmunch commented on src/community/services/community.service.ts
> +      //   const bubble = this.rainbow.bubbles.getBubbleById(community.community_id);
Oui

2024-12-14 14:59 UTC, axelmunch commented on src/community/services/community.service.ts
> +  async searchCommunities(search: string): Promise<Community[]> {
Ajout de la requête SQL parfum nature

2024-12-27 14:59 UTC, maelehrhard approved these changes

2024-12-27 16:14 UTC, merged